Pages/AddBooks.cshtml.cs
#nullable enable
using System;
using System.Collections.Generic;
using System.Diagnostics;
using libraryApi.Models;
using libraryApi.Models.BookManagement;
using libraryApi.Models.Books;
using libraryApi.Models.SeriesManagement;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace libraryApi.Pages
{
    public class AddBooks : PageModel
    {
        // Properties
        public bool Error { get; set; }
        public string? ErrorMessage { get; set; }
        public bool Success { get; set; }
        public string? SuccessMessage { get; set; }
        
        // pre-defined parts for form
        public static Series? Series { get; set; }
        public static string? BookType { get; set; }
        public static Author? Author { get; set; }
        public static bool FromSeries { get; set; }
        public static bool FromBooks { get; set; }
        
        // Information for page styling
        public Dictionary<string, string> HeaderItems { get; } =
            new Dictionary<string, string>(2)
            {
                {"active", "Add Books"},
                {"header", "Add books to database"}
            };

        public List<List<string>> Scripts { get; } = new List<List<string>>
        {
            new List<string>()
            {
                "/js/manage_add_form.js",
                "text/javascript"
            }
        };
        
        // Page handlers
        public void OnGet()
        {
            if (!FromSeries)
            {
                Series = null;
                BookType = null;
            }

            if (!FromBooks)
            {
                Author = null;
            }

            FromSeries = false;
            FromBooks = false;
        }

        public void OnGetAdd(string bookType, 
            string numberInSeries, bool completesSeries, string authorFirst, string authorLast,
            string authorInitials, string title, string language, 
            string releaseDate, bool stillAgenda, bool thirdPartyBook,
            bool read, bool tooBoring, bool stillCalibre, bool stillEreader, 
            bool stillBackup, string type, bool novel68, bool audioAvailable, bool audioOnly)
        {
            Error = false;
            Success = false;
            Author? author = null;
            try
            {
                if (string.IsNullOrEmpty(authorFirst) && string.IsNullOrEmpty(authorLast))
                {
                    Error = true;
                    ErrorMessage = "Author firstname or author lastname has to be provided at the least.";
                    return;
                }

                // get author information
                if (Series != null)
                {
                    author = Series.Author;
                }
                else
                {
                    author = Author ?? new Author(authorFirst, authorInitials, authorLast);
                }

                var seriesNr = 0;
                if (Series != null)
                {
                    seriesNr = Series.SeriesNr;
                }
                
                // create book object
                Book? book = null;
                switch (bookType)
                {
                    case "notReleased":
                        book = new NotReleasedBook(author, seriesNr, numberInSeries, title, language, releaseDate,
                            stillAgenda, 0);
                        book.AddToDatabase();
                        var notReleasedBook = (NotReleasedBook) book;
                        BooksManager.NotReleasedBooks[notReleasedBook.TableId] = notReleasedBook;
                        break;
                    case "wanted":
                        book = new WantedBook(author, seriesNr, numberInSeries, title, language, 0);
                        book.AddToDatabase();
                        var wantedBook = (WantedBook) book;
                        BooksManager.WantedBooks[wantedBook.TableId] = wantedBook;
                        break;
                    case "owned":
                        book = new OwnedBook(
                            author, seriesNr, numberInSeries, title,
                            language, 0, stillCalibre, stillEreader,
                            stillBackup, novel68, thirdPartyBook, read,
                            tooBoring, type, audioAvailable,
                            audioOnly, completesSeries);
                        book.AddToDatabase();
                        var ownedBook = (OwnedBook) book;
                        BooksManager.OwnedBooks[ownedBook.BookNr] = ownedBook;
                        break;
                }

                if (book != null)
                {
                    Success = true;
                    SuccessMessage = $"Successfully added book {book} to database.";   
                }
                else
                {
                    Error = true;
                    ErrorMessage = "invalid book type given, select one in the dropdown in the addbooks form.";
                }
            }
            catch (Exception e)
            {
                Error = true;
                ErrorMessage = e.Message;
                // a new author was made that now won't be used, so needs to be deleted from database.
                if (author != null && Author == null && Series == null)
                {
                    author.RemoveFromDatabase();
                }
            }
            finally
            {
                if (SessionController.RemoveCreds)
                {
                    SessionController.DatabaseCreds = null;
                }
                Series = null;
                BookType = null;
                Author = null;
            }
            
        }
    }
}

Pages/Error.cshtml.cs
using System.Collections.Generic;
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace libraryApi.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
        
        // Information for page styling
        public Dictionary<string, string> HeaderItems { get; } =
            new Dictionary<string, string>(2)
            {
                {"active", null},
                {"header", "Error"}
            };

        public List<List<string>> Scripts { get; } = new List<List<string>>();
        
        public ActionResult OnGetDownloadFile()
        {
            return File("Logfile.txt", "application/octet-stream", "log.txt");
        }
    }
}

Pages/Index.cshtml.cs
#nullable enable
using System;
using System.Collections;
using System.Collections.Generic;
using libraryApi.Data;
using libraryApi.Models;
using libraryApi.Models.Agenda;
using libraryApi.Models.BookManagement;
using libraryApi.Models.Books;
using libraryApi.Models.Logging;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace libraryApi.Pages
{
    public class IndexModel : PageModel
    {
        public bool Success { get; set; }
        public string? SuccessMessage { get; private set; }
        public bool Error { get; set; }
        public string? ErrorMessage { get; set; }

        // Information for page styling
        public Dictionary<string, string> HeaderItems { get; } =
            new Dictionary<string, string>(2)
            {
                {"active", "Home"},
                {"header", "Task request"}
            };

        public List<List<string>> Scripts { get; } = new List<List<string>>
        {
            new List<string>
            {
                "/js/manageDatatablesHome.js",
                "text/javascript"
            }
        };

        public static List<Dictionary<string, object>>? StillAgenda { get; set; }
        public static List<Dictionary<string, object>>? StillCalibre { get; set; }
        public static List<Dictionary<string, object>>? StillEreader { get; set; }
        public static List<Dictionary<string, object>>? StillBackup { get; set; }

        // Handler methods
        public void OnGet()
        {
            if (SessionController.DatabaseCreds == null) return;
            StillAgenda = ViewManager.GetStillAgenda();
            StillCalibre = ViewManager.GetStillCalibre();
            StillEreader = ViewManager.GetStillEreader();
            StillBackup = ViewManager.GetStillBackup();

        }

        public void OnGetOpenCalibre()
        {
            System.Diagnostics.Process process = new System.Diagnostics.Process();
            System.Diagnostics.ProcessStartInfo startInfo = new System.Diagnostics.ProcessStartInfo();
            startInfo.WindowStyle = System.Diagnostics.ProcessWindowStyle.Hidden;
            startInfo.FileName = "cmd.exe";
            startInfo.Arguments = "/C calibre";
            process.StartInfo = startInfo;
            process.Start();
        }

        public void OnGetUpdateCalibre()
        {
            Success = false;
            SuccessMessage = null;
            Error = false;
            ErrorMessage = null;

            try
            {
                // update database
                var query = "update mijn_boeken set NOG_CALIBRE = '0' where NOG_CALIBRE = '1'";
                var manager = ConnectionManager.DefaultManager();
                manager.Update(query);

                // update object
                SessionController.OwnedManager ??= new OwnedManager();
                foreach (var bookInfo in StillCalibre)
                {
                    var id = int.Parse(bookInfo["BOEKNR"].ToString());
                    var book = BooksManager.OwnedBooks[id];
                    book.StillCalibre = false;
                }

                Success = true;
                SuccessMessage = "Successfully marked all books as not needing calibre.";
            }
            catch (Exception e)
            {
                Error = true;
                ErrorMessage = e.Message;
            }
            finally
            {
                StillCalibre = ViewManager.GetStillCalibre();
                if (SessionController.RemoveCreds)
                {
                    SessionController.DatabaseCreds = null;
                }
            }
        }

        public void OnGetUpdateBackup()
        {
            Success = false;
            SuccessMessage = null;
            Error = false;
            ErrorMessage = null;

            try
            {
                // update database
                var query = "update mijn_boeken set NOG_BACKUP = '0' where NOG_BACKUP = '1'";
                var manager = ConnectionManager.DefaultManager();
                manager.Update(query);

                // update object
                SessionController.OwnedManager ??= new OwnedManager();
                foreach (var bookInfo in StillBackup)
                {
                    var id = int.Parse(bookInfo["BOEKNR"].ToString());
                    var book = BooksManager.OwnedBooks[id];
                    book.StillBackup = false;
                }

                Success = true;
                SuccessMessage = "Successfully marked all books as not needing backup.";
            }
            catch (Exception e)
            {
                Error = true;
                ErrorMessage = e.Message;
            }
            finally
            {
                StillBackup = ViewManager.GetStillBackup();
                if (SessionController.RemoveCreds)
                {
                    SessionController.DatabaseCreds = null;
                }
            }
        }

        public void OnGetUpdateEreader()
        {
            Success = false;
            SuccessMessage = null;
            Error = false;
            ErrorMessage = null;

            try
            {
                // update database
                var query = "update mijn_boeken set NOG_EREADER = '0' where NOG_EREADER = '1'";
                var manager = ConnectionManager.DefaultManager();
                manager.Update(query);

                // update object
                SessionController.OwnedManager ??= new OwnedManager();
                foreach (var bookInfo in StillEreader)
                {
                    var id = int.Parse(bookInfo["BOEKNR"].ToString());
                    var book = BooksManager.OwnedBooks[id];
                    book.StillEReader = false;
                }

                Success = true;
                SuccessMessage = "Successfully marked all books as not needing to be added to the ereader.";
            }
            catch (Exception e)
            {
                Error = true;
                ErrorMessage = e.Message;
            }
            finally
            {
                StillEreader = ViewManager.GetStillEreader();
                if (SessionController.RemoveCreds)
                {
                    SessionController.DatabaseCreds = null;
                }
            }
        }

        public void OnGetAgenda()
        {
            Success = false;
            SuccessMessage = null;
            Error = false;
            ErrorMessage = null;
            
            var manager = new AgendaManager();
            // gather books needed
            foreach (var bookInfo in StillAgenda)
            {
                var id = int.Parse(bookInfo["ID"].ToString());
                var book = BooksManager.NotReleasedBooks[id];
                try
                {
                    manager.AddToAgenda(book);
                    Success = true;
                    SuccessMessage = SuccessMessage == null
                        ? $"Successfully added {book}"
                        : $"{SuccessMessage}\nand {book}";
                }
                catch (Exception e)
                {
                    Error = true;
                    if (ErrorMessage != null)
                    {
                        ErrorMessage = $"{ErrorMessage}\nSomething went wrong while adding book {book}: {e.Message}.";
                    }
                    else
                    {
                        ErrorMessage = $"Something went wrong while adding book {book}: {e.Message}";
                    }
                }
            }

            StillAgenda = ViewManager.GetStillAgenda();
            if (SessionController.RemoveCreds)
            {
                SessionController.DatabaseCreds = null;
            }

            if (Success)
            {
                SuccessMessage = $"{SuccessMessage}\nTo agenda.";
            }
        }

        /**
         * Used to convert all the released books to wanted books.
         */
        public void OnGetConvertReleased()
        {
            try
            {
                Success = false;
                SuccessMessage = null;
                Error = false;
                SessionController.NotReleasedManager.UpdateReleasedBooks();
                var conversions = SessionController.NotReleasedManager.Logger.Conversions["not_released"];
                foreach (var (original, converted) in conversions)
                {
                    if (converted == null)
                    {
                        Error = true;
                    }
                    else
                    {
                        Success = true;
                        SuccessMessage = SuccessMessage == null
                            ? $"Successfully converted {original}"
                            : $"{SuccessMessage}\nand {original}";
                    }
                }

                if (Success)
                {
                    SuccessMessage = $"{SuccessMessage}\nto wanted book(s)";
                }
            }
            catch (Exception e)
            {
                Error = true;
                Success = false;
                ErrorMessage = e.Message;
            }
            finally
            {
                if (SessionController.RemoveCreds)
                {
                    SessionController.DatabaseCreds = null;
                }
            }
        }
    }
}

Pages/Index.cshtml
@page "{handler?}"
@using libraryApi.Models
@using libraryApi.Models.BookManagement
@using libraryApi.Models.SeriesManagement
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="inhoud">
@if (Model.Error)
{
    @if (!string.IsNullOrEmpty(Model.ErrorMessage))
    {
        <p class="red">
            @Model.ErrorMessage
        </p>
    }
    else
    {
        <p class="red">Something went wrong, see the
            <a asp-page-handler="DownloadFile" asp-page="/Error">log</a> file for details.</p>
    }
}

@if (Model.Success)
{
    <p class="green">
        @(Model.SuccessMessage ?? "Data successfully retrieved.")
    </p>
}

<h2>Tasks to be done</h2>
@if (SessionController.DatabaseCreds != null)
{
    // TODO: statistics
    <!-- Tab panes -->
    <ul class="nav nav-tabs">
        <li><a href="#released" class="active" data-toggle="tab"> Newly Released Books </a></li>
        <li><a href="#calender" data-toggle="tab"> To Add To Agenda </a></li>
        <li><a href="#calibre" data-toggle="tab"> To Modify In Calibre </a></li>
        <li><a href="#backup" data-toggle="tab"> To Add To Backup </a></li>
        <li><a href="#ereader" data-toggle="tab"> To Add To Ereader </a></li>
    </ul>
    <div class="tab-content">
    <div class="tab-pane fade in active" id="released">
        @{ SessionController.NotReleasedManager ??= new NotReleasedManager(); }
        <form>
            <button type="submit" asp-page-handler="ConvertReleased" class="btn btn-default">Convert all to wanted books</button>
        </form>
        <table class="table table-striped table-primary" id="datatable_released">
            <thead>
            <tr>
                <th>Series</th>
                <th>Number in series</th>
                <th>Author</th>
                <th>Title</th>
                <th>Language</th>
                <th>Release date</th>
            </tr>
            </thead>
            <tbody>
            @foreach (var notReleasedBook in BooksManager.NotReleasedBooks.Values)
            {
                if (notReleasedBook.WasReleased())
                {
                    <tr>
                        <td>
                            @if (notReleasedBook.Series != null && notReleasedBook.Series.SeriesNr > 0)
                            {
                                @notReleasedBook.Series.Name
                            }
                            else
                            {
                                @("Null")
                            }
                        </td>
                        <td>
                            @if (!string.IsNullOrEmpty(notReleasedBook.NumberInSeries))
                            {
                                @notReleasedBook.NumberInSeries
                            }
                            else
                            {
                                @("Null")
                            }
                        </td>
                        <td>
                            @notReleasedBook.Author.FullName
                        </td>
                        <td>
                            @notReleasedBook.Title
                        </td>
                        <td>
                            @notReleasedBook.Language
                        </td>
                        <td>
                            @(notReleasedBook.ReleaseDate ?? "unknown")
                        </td>
                    </tr>
                }
            }
            </tbody>
        </table>
    </div>
    <div class="tab-pane fade in" id="calender">
        <form>
            <button type="submit" asp-page-handler="Agenda" class="btn btn-default">Add all to agenda</button>
        </form>
        <table class="table table-striped table-primary" id="datatable_agenda">
            <thead>
            <tr>
                <th>Title</th>
                <th>Series</th>
                <th>Number in Series</th>
                <th>Release Date</th>
            </tr>
            </thead>
            <tbody>
            @foreach (var book in IndexModel.StillAgenda)
            {
                <tr>
                    <td>@book["TITEL"].ToString()</td>
                    <td>
                        @{ var seriesNr = book["SERIENR"].ToString(); }
                        @if (!string.IsNullOrEmpty(seriesNr) && seriesNr != "0")
                        {
                            SessionController.SeriesManager ??= new SeriesManager();
                            @(SessionController.SeriesManager.Series[int.Parse(seriesNr)].Name)
                        }
                        else
                        {
                            @("Null")
                        }
                    </td>
                    <td>
                        @if (!string.IsNullOrEmpty(seriesNr) && seriesNr != "0"
                             && !string.IsNullOrEmpty(book["NUMMER_IN_SERIE"].ToString()))
                        {
                            @book["NUMMER_IN_SERIE"].ToString()
                            ;
                        }
                        else
                        {
                            @("Null")
                        }
                    </td>
                    <td>@book["DATUM_UITKOMST"].ToString()</td>
                </tr>
            }
            </tbody>
        </table>
    </div>
    <div class="tab-pane fade in" id="calibre">
        <form>
            <button type="submit" asp-page-handler="OpenCalibre" class="btn btn-default">Launch Calibre application</button>
            <button type="submit" asp-page-handler="UpdateCalibre" class="btn btn-default float-right">Mark all as done</button>
        </form>
        <table class="table table-striped table-primary" id="datatable_calibre">
            <thead>
            <tr>
                <th>Title</th>
                <th>Series</th>
                <th>Number in Series</th>
                <th>Author</th>
            </tr>
            </thead>
            <tbody>
            @{
                SessionController.OwnedManager ??= new OwnedManager();
            }
            @foreach (var bookInfo in IndexModel.StillCalibre)
            {
                <tr>
                    @{ var book = BooksManager.OwnedBooks[int.Parse(bookInfo["BOEKNR"].ToString())]; }
                    <td>@book.Title</td>
                    <td>
                        @if (book.Series != null && book.Series.SeriesNr > 0)
                        {
                            @(book.Series.Name)
                        }
                        else
                        {
                            @("Null")
                        }
                    </td>
                    <td>
                        @if (book.Series != null && book.Series.SeriesNr > 0
                             && !string.IsNullOrEmpty(book.NumberInSeries))
                        {
                            @book.NumberInSeries
                        }
                        else
                        {
                            @("Null")
                        }
                    </td>
                    <td>
                        @book.Author.FullName
                    </td>
                </tr>
            }
            </tbody>
        </table>
    </div>
    <div class="tab-pane fade in" id="backup">
        <form>
            <button type="submit" asp-page-handler="UpdateBackup" class="btn btn-default">Mark all as transferred</button>
        </form>
        <table class="table table-striped table-primary" id="datatable_backup">
            <thead>
            <tr>
                <th>Title</th>
                <th>Series</th>
                <th>Number in Series</th>
                <th>Author</th>
            </tr>
            </thead>
            <tbody>
            @{
                SessionController.OwnedManager ??= new OwnedManager();
            }
            @foreach (var bookInfo in IndexModel.StillBackup)
            {
                <tr>
                    @{ var book = BooksManager.OwnedBooks[int.Parse(bookInfo["BOEKNR"].ToString())]; }
                    <td>@book.Title</td>
                    <td>
                        @if (book.Series != null && book.Series.SeriesNr > 0)
                        {
                            @(book.Series.Name)
                        }
                        else
                        {
                            @("Null")
                        }
                    </td>
                    <td>
                        @if (book.Series != null && book.Series.SeriesNr > 0
                             && !string.IsNullOrEmpty(book.NumberInSeries))
                        {
                            @book.NumberInSeries
                        }
                        else
                        {
                            @("Null")
                        }
                    </td>
                    <td>
                        @book.Author.FullName
                    </td>
                </tr>
            }
            </tbody>
        </table>
    </div>
    <div class="tab-pane fade in" id="ereader">
        <form>
            <button type="submit" asp-page-handler="UpdateEreader" class="btn btn-default">Mark all as transferred</button>
        </form>
        <table class="table table-striped table-primary" id="datatable_ereader">
            <thead>
            <tr>
                <th>Title</th>
                <th>Series</th>
                <th>Number in Series</th>
                <th>Author</th>
            </tr>
            </thead>
            <tbody>
            @{
                SessionController.OwnedManager ??= new OwnedManager();
            }
            @foreach (var bookInfo in IndexModel.StillEreader)
            {
                <tr>
                    @{ var book = BooksManager.OwnedBooks[int.Parse(bookInfo["BOEKNR"].ToString())]; }
                    <td>@book.Title</td>
                    <td>
                        @if (book.Series != null && book.Series.SeriesNr > 0)
                        {
                            @(book.Series.Name)
                        }
                        else
                        {
                            @("Null")
                        }
                    </td>
                    <td>
                        @if (book.Series != null && book.Series.SeriesNr > 0
                             && !string.IsNullOrEmpty(book.NumberInSeries))
                        {
                            @book.NumberInSeries
                        }
                        else
                        {
                            @("Null")
                        }
                    </td>
                    <td>
                        @book.Author.FullName
                    </td>
                </tr>
            }
            </tbody>
        </table>
    </div>
    </div>
}
else
{
    <p>Login to database to see tasks that need to be done.</p>
}
</div>

Pages/SeriesPicker.cshtml
@page "{handler?}"
@using libraryApi.Models
@using libraryApi.Models.BookManagement
@model SeriesPicker
@{
  ViewData["Title"] = "Series generator";
}

<div class="inhoud">
  @if (Model.Error)
  {
    @if (!string.IsNullOrEmpty(Model.ErrorMessage))
    {
      <p class="red">
        @Model.ErrorMessage
      </p>
    }
    else
    {
      <p class="red">Something went wrong, see the
        <a asp-page-handler="DownloadFile" asp-page="/Error">log</a> file for details.</p>
    }
  }

  @if (Model.Success)
  {
    <p class="green">
      @(Model.SuccessMessage)
    </p>
  }

  <div class="text-center mb-1">
    @if (SessionController.DatabaseCreds != null)
    {
      <form>
        <label class="label">Amount of suggestions <input type="number" class="form-control" name="amount"/></label>
        <br/>
        <input type="submit" value="Pick series" asp-page-handler="Random" />
      </form>
    }
    else
    {
      <p>Login to database before asking for series</p>
    }
  </div>

  @if (SeriesPicker.PickedSeries.Count > 0)
  {
    SessionController.OwnedManager ??= new OwnedManager();
    <table class="table table-bordered table-hover table-primary table-responsive table-striped">
        <thead>
        <tr>
          <th>Series number</th>
          <th>Name</th>
          <th>Author</th>
          <th>Amount of books</th>
          <th>Rating</th>
          <th>Increase Rating</th>
          <th>Decrease Rating</th>
        </tr>
        </thead>
        <tbody>
        @foreach (var (seriesNum, series) in SeriesPicker.PickedSeries)
        {
          <tr>
            <td>@seriesNum.ToString()</td>
            <td>
              @series.Name
            </td>
            <td>
              @series.Author.FullName
            </td>
            <td>
              @{
                int novels = 0;
                int main = 0;
                foreach (var book in BooksManager.SeriesBooks[seriesNum])
                {
                  // companion novel
                  if (string.IsNullOrEmpty(book.NumberInSeries) || book.NumberInSeries.Contains(",") || book.NumberInSeries.Contains("."))
                  {
                    novels++;
                  }
                  else
                  {
                    main++;
                  }
                }
              }
              @main.ToString() (@novels.ToString())
            </td>
            <td>
              @series.Rating.ToString()
            </td>
            <td>
              @if (SessionController.DatabaseCreds != null)
              {
                @if (series.Rating < 5)
                {
                  <form asp-page-handler="ChangeRating" method="get">
                    <input type="hidden" name="seriesId" value="@(seriesNum.ToString())"/>
                    <input type="hidden" name="increase" value="true"/>
                    <input type="submit" value="Increase rating"/>
                  </form>
                }
                else
                {
                  @("Rating has reached its maximum")
                }
              }
              else
              {
                @("Login to database to change series ratings.")
              }
            </td>
            <td>
              @if (SessionController.DatabaseCreds != null)
              {
                @if (series.Rating > 0)
                {
                  <form asp-page-handler="ChangeRating" method="get">
                    <input type="hidden" name="seriesId" value="@(seriesNum.ToString())"/>
                    <input type="hidden" name="increase" value="false"/>
                    <input type="submit" value="Decrease rating"/>
                  </form>
                }
                else
                {
                  @("Rating has reached its minimum")
                }
              }
              else
              {
                @("Login to database to change series ratings.")
              }
            </td>
          </tr>
        }
      </tbody>
    </table>
  }
</div>